### ISSUE TITLE
question about software sources

### ISSUE THREAD

**Issue by 0xaf1f** [amojarro/carrierseq#2]
In your Dockerfile, I see you used apt-get to install most of the packages, but others could also have been had that way: biopython, bwa, and seqtk. fqtrim is the only one not in the repos. I'm asking because the Debian Med group does a lot of work to make these available, and a container is a pretty good use case for them.

**Comment by amojarro** [comment]
The Dockerfile has been updated.

**Comment by 0xaf1f** [comment]
Thanks. I've seen lots of container definitions not using apt-get for the available bioinformatics software, so was wondering if there was a particular reason for that trend. I guess Debian Med needs to do more promotion.
